# Generated by Django 4.2 on 2023-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todayapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-05-21'),
            preserve_default=False,
        ),
    ]
